image: ubuntu:latest

services:
  - docker:dind

stages:
  - build
  - test

build:
  stage: build
  script:
    - echo run tests in this section

test-stories:
  stage: test
  script:
    - sadd-apt-repository universe
    - apt-get update
    - apt-get install -y python3-pip
    - pip3 install --upgrade setuptools
    - pip3 install docker-compose
    - docker image prune -f
    - docker-compose build --no-cache
    - docker-compose up -d