# version: "1.0"

services:
  rasa:
    container_name: rasax
    build: .
    networks: [ 'rasa-network' ]
    ports:
      - "5005:5005"
      - "5002:5002"
    working_dir: /root
    volumes:
      - ./:/root:cached
    environment:
      - RASA_X_PASSWORD=${RASA_X_PASSWORD}
      - RASA_TOKEN=${RASA_TOKEN}
      - PASSWORD_SALT=${PASSWORD_SALT}
      - JWT_SECRET=${JWT_SECRET}
    #FOR PRODUCTION, ADD THIS TAG: --production
    command: bash -c "rasa x --no-prompt --enable-api --endpoints endpoints.yml --port 5005 --cors "*" --debug --log-file LOG_FILE && rasa data validate --fail-on-warnings --max-history 5 && rasa train"
  action_server:
    image: rasa/rasa-sdk:latest
    networks: [ 'rasa-network' ]
    ports:
      - "5055:5055"
    volumes:
      - "./actions:/app/actions"

networks: { rasa-network: { } }