version: "3.4"

services:
  rasa:
    container_name: rasax
    build: .
    networks: ['rasa-network']
    ports:
      - "5005:5005"
      - "5002:5002"
    working_dir: /root
    volumes:
      - ./:/root:cached
    environment:
      - RASA_X_PASSWORD=${RASA_X_PASSWORD}
    #FOR PRODUCTION, ADD THIS TAG: --production
    command: rasa x --no-prompt --enable-api --endpoints docker-local/endpoints.yml --port 5005 --cors "*" --debug --log-file LOG_FILE
  action_server:
    image: rasa/rasa-sdk:latest
    networks: [ 'rasa-network' ]
    ports:
      - "5055:5055"
    volumes:
      - "./actions:/app/actions"

networks: { rasa-network: { } }